name: foe

services:
  foe:
    build:
      context: .
      dockerfile: Dockerfile
      
    image: foe-app:latest
    container_name: foe-app-prod
    restart: unless-stopped
    ports:      
      - "${APP_PORT:-3417}:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
